// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file test/schemaregistry/serde/validation_widget.proto (package test, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_confluent_meta } from "../../../confluent/meta_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file test/schemaregistry/serde/validation_widget.proto.
 */
export const file_test_schemaregistry_serde_validation_widget: GenFile = /*@__PURE__*/
  fileDesc("CjF0ZXN0L3NjaGVtYXJlZ2lzdHJ5L3NlcmRlL3ZhbGlkYXRpb25fd2lkZ2V0LnByb3RvEgR0ZXN0IrEBChBWYWxpZGF0aW9uUGVyc29uEkQKA2FnZRgBIAEoBUI3gkQ0IjIKC2FnZVBvc2l0aXZlEhhhZ2UgbXVzdCBub3QgYmUgbmVnYXRpdmUaCXRoaXMgPj0gMBIxCgRuYW1lGAIgASgJQiOCRCAiHgoMbmFtZU5vdEVtcHR5Gg5zaXplKHRoaXMpID4gMDokgkQhIh8KDGFnZU5vdEluc2FuZRoPdGhpcy5hZ2UgPD0gMTUwIjAKD1ZhbGlkYXRpb25Jbm5lchIdCgF4GAEgASgFQhKCRA8iDQoBchoIdGhpcyA+IDAiOAoOVmFsaWRhdGlvbkl0ZW0SCQoBdhgBIAEoBTobgkQYIhYKCGl0ZW1SdWxlGgp0aGlzLnYgPiAwIssCCg9WYWxpZGF0aW9uT3V0ZXISJAoFaW5uZXIYASABKAsyFS50ZXN0LlZhbGlkYXRpb25Jbm5lchIjCgVpdGVtcxgCIAMoCzIULnRlc3QuVmFsaWRhdGlvbkl0ZW0SOAoFbWF5YmUYAyABKAlCJIJEISIfCg1tYXliZU5vdEVtcHR5Gg5zaXplKHRoaXMpID4gMEgAiAEBEjEKBmxhYmVscxgEIAMoCzIhLnRlc3QuVmFsaWRhdGlvbk91dGVyLkxhYmVsc0VudHJ5EjEKBHRhZ3MYBSADKAlCI4JEICIeCgx0YWdzTm90RW1wdHkaDnNpemUodGhpcykgPiAwGkMKC0xhYmVsc0VudHJ5EgsKA2tleRgBIAEoCRIjCgV2YWx1ZRgCIAEoCzIULnRlc3QuVmFsaWRhdGlvbkl0ZW06AjgBQggKBl9tYXliZSJgCg9WYWxpZGF0aW9uRXZlbnQSTQoKY3JlYXRlZF9hdBgBIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBCHYJEGiIYCglub3RGdXR1cmUaC3RoaXMgPD0gbm93InQKGFZhbGlkYXRpb25EeW5hbWljTWVzc2FnZRJYCgNhZ2UYASABKAVCS4JESCJGCgZhZ2VNc2caPHRoaXMgPj0gMCA/ICcnIDogJ2FnZSBtdXN0IGJlIHBvc2l0aXZlLCBnb3QgJyArIHN0cmluZyh0aGlzKUIJWgcuLi90ZXN0YgZwcm90bzM", [file_confluent_meta, file_google_protobuf_timestamp]);

/**
 * @generated from message test.ValidationPerson
 */
export type ValidationPerson = Message<"test.ValidationPerson"> & {
  /**
   * @generated from field: int32 age = 1;
   */
  age: number;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message test.ValidationPerson.
 * Use `create(ValidationPersonSchema)` to create a new message.
 */
export const ValidationPersonSchema: GenMessage<ValidationPerson> = /*@__PURE__*/
  messageDesc(file_test_schemaregistry_serde_validation_widget, 0);

/**
 * @generated from message test.ValidationInner
 */
export type ValidationInner = Message<"test.ValidationInner"> & {
  /**
   * @generated from field: int32 x = 1;
   */
  x: number;
};

/**
 * Describes the message test.ValidationInner.
 * Use `create(ValidationInnerSchema)` to create a new message.
 */
export const ValidationInnerSchema: GenMessage<ValidationInner> = /*@__PURE__*/
  messageDesc(file_test_schemaregistry_serde_validation_widget, 1);

/**
 * @generated from message test.ValidationItem
 */
export type ValidationItem = Message<"test.ValidationItem"> & {
  /**
   * @generated from field: int32 v = 1;
   */
  v: number;
};

/**
 * Describes the message test.ValidationItem.
 * Use `create(ValidationItemSchema)` to create a new message.
 */
export const ValidationItemSchema: GenMessage<ValidationItem> = /*@__PURE__*/
  messageDesc(file_test_schemaregistry_serde_validation_widget, 2);

/**
 * @generated from message test.ValidationOuter
 */
export type ValidationOuter = Message<"test.ValidationOuter"> & {
  /**
   * @generated from field: test.ValidationInner inner = 1;
   */
  inner?: ValidationInner | undefined;

  /**
   * @generated from field: repeated test.ValidationItem items = 2;
   */
  items: ValidationItem[];

  /**
   * @generated from field: optional string maybe = 3;
   */
  maybe?: string | undefined;

  /**
   * @generated from field: map<string, test.ValidationItem> labels = 4;
   */
  labels: { [key: string]: ValidationItem };

  /**
   * @generated from field: repeated string tags = 5;
   */
  tags: string[];
};

/**
 * Describes the message test.ValidationOuter.
 * Use `create(ValidationOuterSchema)` to create a new message.
 */
export const ValidationOuterSchema: GenMessage<ValidationOuter> = /*@__PURE__*/
  messageDesc(file_test_schemaregistry_serde_validation_widget, 3);

/**
 * @generated from message test.ValidationEvent
 */
export type ValidationEvent = Message<"test.ValidationEvent"> & {
  /**
   * @generated from field: google.protobuf.Timestamp created_at = 1;
   */
  createdAt?: Timestamp | undefined;
};

/**
 * Describes the message test.ValidationEvent.
 * Use `create(ValidationEventSchema)` to create a new message.
 */
export const ValidationEventSchema: GenMessage<ValidationEvent> = /*@__PURE__*/
  messageDesc(file_test_schemaregistry_serde_validation_widget, 4);

/**
 * @generated from message test.ValidationDynamicMessage
 */
export type ValidationDynamicMessage = Message<"test.ValidationDynamicMessage"> & {
  /**
   * @generated from field: int32 age = 1;
   */
  age: number;
};

/**
 * Describes the message test.ValidationDynamicMessage.
 * Use `create(ValidationDynamicMessageSchema)` to create a new message.
 */
export const ValidationDynamicMessageSchema: GenMessage<ValidationDynamicMessage> = /*@__PURE__*/
  messageDesc(file_test_schemaregistry_serde_validation_widget, 5);

