// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file test/schemaregistry/serde/value_types.proto (package test, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_confluent_meta } from "../../../confluent/meta_pb";
import type { Decimal } from "../../../confluent/types/decimal_pb";
import { file_confluent_types_decimal } from "../../../confluent/types/decimal_pb";
import type { Variant } from "../../../confluent/types/variant_pb";
import { file_confluent_types_variant } from "../../../confluent/types/variant_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file test/schemaregistry/serde/value_types.proto.
 */
export const file_test_schemaregistry_serde_value_types: GenFile = /*@__PURE__*/
  fileDesc("Cit0ZXN0L3NjaGVtYXJlZ2lzdHJ5L3NlcmRlL3ZhbHVlX3R5cGVzLnByb3RvEgR0ZXN0Is8BCgpWYWx1ZVR5cGVzEjQKBmFtb3VudBgBIAEoCzIXLmNvbmZsdWVudC50eXBlLkRlY2ltYWxCC4JECBoGQU1PVU5UEi8KAnRzGAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEIHgkQEGgJUUxIwCgRkYXRhGAMgASgLMhcuY29uZmx1ZW50LnR5cGUuVmFyaWFudEIJgkQGGgREQVRBEhkKBWxhYmVsGAQgASgJQgqCRAcaBUxBQkVMEg0KBWNvdW50GAUgASgFQglaBy4uL3Rlc3RiBnByb3RvMw", [file_confluent_meta, file_confluent_types_decimal, file_confluent_types_variant, file_google_protobuf_timestamp]);

/**
 * The three value types protobuf carries as messages, plus a scalar. Tagged so a CEL_FIELD
 * rule can be scoped to one field at a time.
 *
 * @generated from message test.ValueTypes
 */
export type ValueTypes = Message<"test.ValueTypes"> & {
  /**
   * @generated from field: confluent.type.Decimal amount = 1;
   */
  amount?: Decimal | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp ts = 2;
   */
  ts?: Timestamp | undefined;

  /**
   * @generated from field: confluent.type.Variant data = 3;
   */
  data?: Variant | undefined;

  /**
   * @generated from field: string label = 4;
   */
  label: string;

  /**
   * @generated from field: int32 count = 5;
   */
  count: number;
};

/**
 * Describes the message test.ValueTypes.
 * Use `create(ValueTypesSchema)` to create a new message.
 */
export const ValueTypesSchema: GenMessage<ValueTypes> = /*@__PURE__*/
  messageDesc(file_test_schemaregistry_serde_value_types, 0);

