// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file test/schemaregistry/serde/value_type_rules.proto (package test, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_confluent_meta } from "../../../confluent/meta_pb";
import type { Decimal } from "../../../confluent/type/decimal_pb";
import { file_confluent_type_decimal } from "../../../confluent/type/decimal_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file test/schemaregistry/serde/value_type_rules.proto.
 */
export const file_test_schemaregistry_serde_value_type_rules: GenFile = /*@__PURE__*/
  fileDesc("CjB0ZXN0L3NjaGVtYXJlZ2lzdHJ5L3NlcmRlL3ZhbHVlX3R5cGVfcnVsZXMucHJvdG8SBHRlc3QizwIKEElubGluZVZhbHVlVHlwZXMSWwoGYW1vdW50GAEgASgLMhcuY29uZmx1ZW50LnR5cGUuRGVjaW1hbEIygkQvIi0KBmZsZERlYxojZGVjaW1hbHMuZ3QodGhpcywgZGVjaW1hbCgnMTAuMDAnKSkSXgoCdHMYAiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wQjaCRDMiMQoFZmxkVHMaKHRoaXMgPiB0aW1lc3RhbXAoJzIwMDAtMDEtMDFUMDA6MDA6MDBaJykSDQoFbGFiZWwYAyABKAk6b4JEbCI0CgZtc2dEZWMaKmRlY2ltYWxzLmd0KHRoaXMuYW1vdW50LCBkZWNpbWFsKCcxMC4wMCcpKSI0CgVtc2dUcxordGhpcy50cyA+IHRpbWVzdGFtcCgnMjAwMC0wMS0wMVQwMDowMDowMFonKSLwAwoTVmFsdWVUeXBlQ29udGFpbmVycxJnCgdhbW91bnRzGAEgAygLMhcuY29uZmx1ZW50LnR5cGUuRGVjaW1hbEI9gkQ6GgdBTU9VTlRTIi8KBmZsZEFycholZGVjaW1hbHMuZ3QodGhpc1swXSwgZGVjaW1hbCgnMS4wMCcpKRJMCgphbW91bnRfbWFwGAIgAygLMigudGVzdC5WYWx1ZVR5cGVDb250YWluZXJzLkFtb3VudE1hcEVudHJ5Qg6CRAsaCUFNT1VOVE1BUBIlCgZuZXN0ZWQYAyABKAsyFS50ZXN0LlZhbHVlVHlwZU5lc3RlZBIZCgVsYWJlbBgEIAEoCUIKgkQHGgVMQUJFTBIZCgVjb2RlcxgFIAMoCUIKgkQHGgVDT0RFUxpJCg5BbW91bnRNYXBFbnRyeRILCgNrZXkYASABKAkSJgoFdmFsdWUYAiABKAsyFy5jb25mbHVlbnQudHlwZS5EZWNpbWFsOgI4ATp6gkR3IjcKBm1zZ0FychotZGVjaW1hbHMuZ3QodGhpcy5hbW91bnRzWzBdLCBkZWNpbWFsKCcxLjAwJykpIjwKCW1zZ05lc3RlZBovZGVjaW1hbHMuZ3QodGhpcy5uZXN0ZWQuaW5uZXIsIGRlY2ltYWwoJzEuMDAnKSkidQoPVmFsdWVUeXBlTmVzdGVkEmIKBWlubmVyGAEgASgLMhcuY29uZmx1ZW50LnR5cGUuRGVjaW1hbEI6gkQ3GgVJTk5FUiIuCghmbGRJbm5lchoiZGVjaW1hbHMuZ3QodGhpcywgZGVjaW1hbCgnMS4wMCcpKWIGcHJvdG8z", [file_confluent_meta, file_confluent_type_decimal, file_google_protobuf_timestamp]);

/**
 * Inline rules on the two value types, at message and field level, so both can be exercised
 * over an UNSET field. Mirrors the reference's own fixture so the clients are compared against
 * the same rules.
 *
 * @generated from message test.InlineValueTypes
 */
export type InlineValueTypes = Message<"test.InlineValueTypes"> & {
  /**
   * @generated from field: confluent.type.Decimal amount = 1;
   */
  amount?: Decimal | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp ts = 2;
   */
  ts?: Timestamp | undefined;

  /**
   * @generated from field: string label = 3;
   */
  label: string;
};

/**
 * Describes the message test.InlineValueTypes.
 * Use `create(InlineValueTypesSchema)` to create a new message.
 */
export const InlineValueTypesSchema: GenMessage<InlineValueTypes> = /*@__PURE__*/
  messageDesc(file_test_schemaregistry_serde_value_type_rules, 0);

/**
 * A container message carrying BOTH inline rules and tags, so one fixture serves every way a
 * rule can reach a value type inside a container: inline rules, message-level selection, a
 * tagged CEL_FIELD rule, and a message-level transform.
 *
 * @generated from message test.ValueTypeContainers
 */
export type ValueTypeContainers = Message<"test.ValueTypeContainers"> & {
  /**
   * @generated from field: repeated confluent.type.Decimal amounts = 1;
   */
  amounts: Decimal[];

  /**
   * @generated from field: map<string, confluent.type.Decimal> amount_map = 2;
   */
  amountMap: { [key: string]: Decimal };

  /**
   * @generated from field: test.ValueTypeNested nested = 3;
   */
  nested?: ValueTypeNested | undefined;

  /**
   * Tagged so a rule can target a singular scalar: a singular condition still raises where a
   * repeated one does not.
   *
   * @generated from field: string label = 4;
   */
  label: string;

  /**
   * A tagged repeated scalar. The element type decides whether the list branch reaches
   * transformLeaf or the value-type leaf path.
   *
   * @generated from field: repeated string codes = 5;
   */
  codes: string[];
};

/**
 * Describes the message test.ValueTypeContainers.
 * Use `create(ValueTypeContainersSchema)` to create a new message.
 */
export const ValueTypeContainersSchema: GenMessage<ValueTypeContainers> = /*@__PURE__*/
  messageDesc(file_test_schemaregistry_serde_value_type_rules, 1);

/**
 * @generated from message test.ValueTypeNested
 */
export type ValueTypeNested = Message<"test.ValueTypeNested"> & {
  /**
   * @generated from field: confluent.type.Decimal inner = 1;
   */
  inner?: Decimal | undefined;
};

/**
 * Describes the message test.ValueTypeNested.
 * Use `create(ValueTypeNestedSchema)` to create a new message.
 */
export const ValueTypeNestedSchema: GenMessage<ValueTypeNested> = /*@__PURE__*/
  messageDesc(file_test_schemaregistry_serde_value_type_rules, 2);

