// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file confluent/types/decimal.proto (syntax proto3)
/* eslint-disable */

import type { GenFile } from "@bufbuild/protobuf/codegenv2";
import { fileDesc } from "@bufbuild/protobuf/codegenv2";
import { file_confluent_type_decimal } from "../type/decimal_pb";

/**
 * Describes the file confluent/types/decimal.proto.
 */
export const file_confluent_types_decimal: GenFile = /*@__PURE__*/
  fileDesc("Ch1jb25mbHVlbnQvdHlwZXMvZGVjaW1hbC5wcm90b1AAYgZwcm90bzM", [file_confluent_type_decimal]);

