// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file confluent/types/variant.proto (package confluent.type, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file confluent/types/variant.proto.
 */
export const file_confluent_types_variant: GenFile = /*@__PURE__*/
  fileDesc("Ch1jb25mbHVlbnQvdHlwZXMvdmFyaWFudC5wcm90bxIOY29uZmx1ZW50LnR5cGUiKgoHVmFyaWFudBIQCghtZXRhZGF0YRgBIAEoDBINCgV2YWx1ZRgCIAEoDEIKWgguLi90eXBlc2IGcHJvdG8z");

/**
 * @generated from message confluent.type.Variant
 */
export type Variant = Message<"confluent.type.Variant"> & {
  /**
   * A dictionary of field names used by all objects in the variant value.
   * Encoded as: version header, dictionary size, offset list, and UTF-8 string data.
   *
   * @generated from field: bytes metadata = 1;
   */
  metadata: Uint8Array;

  /**
   * The variant value, which can be a primitive, object, or array.
   * Encoded as: a one-byte header (basic type + type info) followed by the content bytes.
   *
   * @generated from field: bytes value = 2;
   */
  value: Uint8Array;
};

/**
 * Describes the message confluent.type.Variant.
 * Use `create(VariantSchema)` to create a new message.
 */
export const VariantSchema: GenMessage<Variant> = /*@__PURE__*/
  messageDesc(file_confluent_types_variant, 0);

