name: high_throughput
description: Optimized for maximum throughput with large batches and compression

stopping:
  mode: count
  message_count: 1000000
  duration_seconds: 60

producer:
  batch_size: 1000
  compression: lz4
  warmup_messages: 10000
  linger_ms: 5
  acks: 1

consumer:
  fetch_min_bytes: 1048576
  fetch_wait_max_ms: 500
  auto_commit: false

message:
  size: 1024
  key_size: 16

ctp:
  process_time_ms: 0
  concurrency: 4

latency:
  producer_delay_ms: 10
  consumer_delay_ms: 10

runs: 5
warmup_runs: 1

# Additional librdkafka configuration
rdkafka:
  queue.buffering.max.messages: 500000
  queue.buffering.max.ms: 5
