name: sustained_throughput
description: Time-driven benchmark to measure sustained throughput over extended period

stopping:
  mode: time
  message_count: -1
  duration_seconds: 60

producer:
  batch_size: 500
  compression: snappy
  warmup_messages: 5000
  linger_ms: 10
  acks: 1

consumer:
  fetch_min_bytes: 524288
  fetch_wait_max_ms: 500
  auto_commit: false

message:
  size: 512
  key_size: 16

ctp:
  process_time_ms: 1
  concurrency: 2

latency:
  producer_delay_ms: 50
  consumer_delay_ms: 50

runs: 3
warmup_runs: 0
