// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file meta.proto (package confluent, syntax proto3)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { EnumOptions, EnumValueOptions, FieldOptions, FileOptions, MessageOptions } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_descriptor } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file meta.proto.
 */
export const file_meta: GenFile = /*@__PURE__*/
  fileDesc("CgptZXRhLnByb3RvEgljb25mbHVlbnQifQoETWV0YRILCgNkb2MYASABKAkSKwoGcGFyYW1zGAIgAygLMhsuY29uZmx1ZW50Lk1ldGEuUGFyYW1zRW50cnkSDAoEdGFncxgDIAMoCRotCgtQYXJhbXNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBOksKCWZpbGVfbWV0YRIcLmdvb2dsZS5wcm90b2J1Zi5GaWxlT3B0aW9ucxjACCABKAsyDy5jb25mbHVlbnQuTWV0YVIIZmlsZU1ldGE6VAoMbWVzc2FnZV9tZXRhEh8uZ29vZ2xlLnByb3RvYnVmLk1lc3NhZ2VPcHRpb25zGMAIIAEoCzIPLmNvbmZsdWVudC5NZXRhUgttZXNzYWdlTWV0YTpOCgpmaWVsZF9tZXRhEh0uZ29vZ2xlLnByb3RvYnVmLkZpZWxkT3B0aW9ucxjACCABKAsyDy5jb25mbHVlbnQuTWV0YVIJZmllbGRNZXRhOksKCWVudW1fbWV0YRIcLmdvb2dsZS5wcm90b2J1Zi5FbnVtT3B0aW9ucxjACCABKAsyDy5jb25mbHVlbnQuTWV0YVIIZW51bU1ldGE6WwoPZW51bV92YWx1ZV9tZXRhEiEuZ29vZ2xlLnByb3RvYnVmLkVudW1WYWx1ZU9wdGlvbnMYwAggASgLMg8uY29uZmx1ZW50Lk1ldGFSDWVudW1WYWx1ZU1ldGFCDloMLi4vY29uZmx1ZW50YgZwcm90bzM", [file_google_protobuf_descriptor]);

/**
 * @generated from message confluent.Meta
 */
export type Meta = Message<"confluent.Meta"> & {
  /**
   * @generated from field: string doc = 1;
   */
  doc: string;

  /**
   * @generated from field: map<string, string> params = 2;
   */
  params: { [key: string]: string };

  /**
   * @generated from field: repeated string tags = 3;
   */
  tags: string[];
};

/**
 * Describes the message confluent.Meta.
 * Use `create(MetaSchema)` to create a new message.
 */
export const MetaSchema: GenMessage<Meta> = /*@__PURE__*/
  messageDesc(file_meta, 0);

/**
 * @generated from extension: confluent.Meta file_meta = 1088;
 */
export const file_meta$: GenExtension<FileOptions, Meta> = /*@__PURE__*/
  extDesc(file_meta, 0);

/**
 * @generated from extension: confluent.Meta message_meta = 1088;
 */
export const message_meta: GenExtension<MessageOptions, Meta> = /*@__PURE__*/
  extDesc(file_meta, 1);

/**
 * @generated from extension: confluent.Meta field_meta = 1088;
 */
export const field_meta: GenExtension<FieldOptions, Meta> = /*@__PURE__*/
  extDesc(file_meta, 2);

/**
 * @generated from extension: confluent.Meta enum_meta = 1088;
 */
export const enum_meta: GenExtension<EnumOptions, Meta> = /*@__PURE__*/
  extDesc(file_meta, 3);

/**
 * @generated from extension: confluent.Meta enum_value_meta = 1088;
 */
export const enum_value_meta: GenExtension<EnumValueOptions, Meta> = /*@__PURE__*/
  extDesc(file_meta, 4);

