// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file confluent/meta.proto (package confluent, syntax proto3)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { EnumOptions, EnumValueOptions, FieldOptions, FileOptions, MessageOptions } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_descriptor } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file confluent/meta.proto.
 */
export const file_confluent_meta: GenFile = /*@__PURE__*/
  fileDesc("ChRjb25mbHVlbnQvbWV0YS5wcm90bxIJY29uZmx1ZW50Ip0BCgRNZXRhEgsKA2RvYxgBIAEoCRIrCgZwYXJhbXMYAiADKAsyGy5jb25mbHVlbnQuTWV0YS5QYXJhbXNFbnRyeRIMCgR0YWdzGAMgAygJEh4KBXJ1bGVzGAQgAygLMg8uY29uZmx1ZW50LlJ1bGUaLQoLUGFyYW1zRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ASI8CgRSdWxlEgwKBG5hbWUYASABKAkSCwoDZG9jGAIgASgJEgwKBGV4cHIYAyABKAkSCwoDc3FsGAQgASgJOksKCWZpbGVfbWV0YRIcLmdvb2dsZS5wcm90b2J1Zi5GaWxlT3B0aW9ucxjACCABKAsyDy5jb25mbHVlbnQuTWV0YVIIZmlsZU1ldGE6VAoMbWVzc2FnZV9tZXRhEh8uZ29vZ2xlLnByb3RvYnVmLk1lc3NhZ2VPcHRpb25zGMAIIAEoCzIPLmNvbmZsdWVudC5NZXRhUgttZXNzYWdlTWV0YTpOCgpmaWVsZF9tZXRhEh0uZ29vZ2xlLnByb3RvYnVmLkZpZWxkT3B0aW9ucxjACCABKAsyDy5jb25mbHVlbnQuTWV0YVIJZmllbGRNZXRhOksKCWVudW1fbWV0YRIcLmdvb2dsZS5wcm90b2J1Zi5FbnVtT3B0aW9ucxjACCABKAsyDy5jb25mbHVlbnQuTWV0YVIIZW51bU1ldGE6WwoPZW51bV92YWx1ZV9tZXRhEiEuZ29vZ2xlLnByb3RvYnVmLkVudW1WYWx1ZU9wdGlvbnMYwAggASgLMg8uY29uZmx1ZW50Lk1ldGFSDWVudW1WYWx1ZU1ldGFCDloMLi4vY29uZmx1ZW50YgZwcm90bzM", [file_google_protobuf_descriptor]);

/**
 * @generated from message confluent.Meta
 */
export type Meta = Message<"confluent.Meta"> & {
  /**
   * @generated from field: string doc = 1;
   */
  doc: string;

  /**
   * @generated from field: map<string, string> params = 2;
   */
  params: { [key: string]: string };

  /**
   * @generated from field: repeated string tags = 3;
   */
  tags: string[];

  /**
   * @generated from field: repeated confluent.Rule rules = 4;
   */
  rules: Rule[];
};

/**
 * Describes the message confluent.Meta.
 * Use `create(MetaSchema)` to create a new message.
 */
export const MetaSchema: GenMessage<Meta> = /*@__PURE__*/
  messageDesc(file_confluent_meta, 0);

/**
 * @generated from message confluent.Rule
 */
export type Rule = Message<"confluent.Rule"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string doc = 2;
   */
  doc: string;

  /**
   * @generated from field: string expr = 3;
   */
  expr: string;

  /**
   * @generated from field: string sql = 4;
   */
  sql: string;
};

/**
 * Describes the message confluent.Rule.
 * Use `create(RuleSchema)` to create a new message.
 */
export const RuleSchema: GenMessage<Rule> = /*@__PURE__*/
  messageDesc(file_confluent_meta, 1);

/**
 * @generated from extension: confluent.Meta file_meta = 1088;
 */
export const file_meta: GenExtension<FileOptions, Meta> = /*@__PURE__*/
  extDesc(file_confluent_meta, 0);

/**
 * @generated from extension: confluent.Meta message_meta = 1088;
 */
export const message_meta: GenExtension<MessageOptions, Meta> = /*@__PURE__*/
  extDesc(file_confluent_meta, 1);

/**
 * @generated from extension: confluent.Meta field_meta = 1088;
 */
export const field_meta: GenExtension<FieldOptions, Meta> = /*@__PURE__*/
  extDesc(file_confluent_meta, 2);

/**
 * @generated from extension: confluent.Meta enum_meta = 1088;
 */
export const enum_meta: GenExtension<EnumOptions, Meta> = /*@__PURE__*/
  extDesc(file_confluent_meta, 3);

/**
 * @generated from extension: confluent.Meta enum_value_meta = 1088;
 */
export const enum_value_meta: GenExtension<EnumValueOptions, Meta> = /*@__PURE__*/
  extDesc(file_confluent_meta, 4);

