apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ckjs-perf-scale.secretName" . }}
  labels:
    {{- include "ckjs-perf-scale.labels" . | nindent 4 }}
type: Opaque
stringData:
  SASL_PASSWORD: {{ required "kafka.saslPassword is required (provide via -f or --set)" .Values.kafka.saslPassword | quote }}
